#pragma once

#define RPL_WELCOME "001"
#define RPL_YOURHOST "002"
#define RPL_CREATED "003"
#define RPL_MYINFO "004"


#define ERR_NONICKNAMEGIVEN "431"
#define ERR_NICKNAMEINUSE "433"

#define ERR_PASSWDMISMATCH "464"